import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { RegisterTool } from "./register-tool.js";

import { CreateInvoiceTool } from "../tools/create-invoice.tool.js";
import { ReadInvoiceTool } from "../tools/read-invoice.tool.js";
import { SearchInvoicesTool } from "../tools/search-invoices.tool.js";
import { UpdateInvoiceTool } from "../tools/update-invoice.tool.js";
import { CreateAccountTool } from "../tools/create-account.tool.js";
import { UpdateAccountTool } from "../tools/update-account.tool.js";
import { SearchAccountsTool } from "../tools/search-accounts.tool.js";
import { ReadItemTool } from "../tools/read-item.tool.js";
import { SearchItemsTool } from "../tools/search-items.tool.js";
import { CreateItemTool } from "../tools/create-item.tool.js";
import { UpdateItemTool } from "../tools/update-item.tool.js";
import { CreateCustomerTool } from "../tools/create-customer.tool.js";
import { GetCustomerTool } from "../tools/get-customer.tool.js";
import { UpdateCustomerTool } from "../tools/update-customer.tool.js";
import { DeleteCustomerTool } from "../tools/delete-customer.tool.js";
import { SearchCustomersTool } from "../tools/search-customers.tool.js";
import { CreateEstimateTool } from "../tools/create-estimate.tool.js";
import { GetEstimateTool } from "../tools/get-estimate.tool.js";
import { UpdateEstimateTool } from "../tools/update-estimate.tool.js";
import { DeleteEstimateTool } from "../tools/delete-estimate.tool.js";
import { SearchEstimatesTool } from "../tools/search-estimates.tool.js";
import { CreateBillTool } from "../tools/create-bill.tool.js";
import { UpdateBillTool } from "../tools/update-bill.tool.js";
import { DeleteBillTool } from "../tools/delete-bill.tool.js";
import { GetBillTool } from "../tools/get-bill.tool.js";
import { SearchBillsTool } from "../tools/search-bills.tool.js";
import { CreateVendorTool } from "../tools/create-vendor.tool.js";
import { UpdateVendorTool } from "../tools/update-vendor.tool.js";
import { DeleteVendorTool } from "../tools/delete-vendor.tool.js";
import { GetVendorTool } from "../tools/get-vendor.tool.js";
import { SearchVendorsTool } from "../tools/search-vendors.tool.js";
import { CreateEmployeeTool } from "../tools/create-employee.tool.js";
import { GetEmployeeTool } from "../tools/get-employee.tool.js";
import { UpdateEmployeeTool } from "../tools/update-employee.tool.js";
import { SearchEmployeesTool } from "../tools/search-employees.tool.js";
import { CreateJournalEntryTool } from "../tools/create-journal-entry.tool.js";
import { GetJournalEntryTool } from "../tools/get-journal-entry.tool.js";
import { UpdateJournalEntryTool } from "../tools/update-journal-entry.tool.js";
import { DeleteJournalEntryTool } from "../tools/delete-journal-entry.tool.js";
import { SearchJournalEntriesTool } from "../tools/search-journal-entries.tool.js";
import { CreateBillPaymentTool } from "../tools/create-bill-payment.tool.js";
import { GetBillPaymentTool } from "../tools/get-bill-payment.tool.js";
import { UpdateBillPaymentTool } from "../tools/update-bill-payment.tool.js";
import { DeleteBillPaymentTool } from "../tools/delete-bill-payment.tool.js";
import { SearchBillPaymentsTool } from "../tools/search-bill-payments.tool.js";
import { CreatePurchaseTool } from "../tools/create-purchase.tool.js";
import { GetPurchaseTool } from "../tools/get-purchase.tool.js";
import { UpdatePurchaseTool } from "../tools/update-purchase.tool.js";
import { DeletePurchaseTool } from "../tools/delete-purchase.tool.js";
import { SearchPurchasesTool } from "../tools/search-purchases.tool.js";
import { GetProfitAndLossTool } from "../tools/get-profit-and-loss.tool.js";
import { GetBalanceSheetTool } from "../tools/get-balance-sheet.tool.js";
import { GetTrialBalanceTool } from "../tools/get-trial-balance.tool.js";
import { GetGeneralLedgerTool } from "../tools/get-general-ledger.tool.js";
import { GetArAgingTool } from "../tools/get-ar-aging.tool.js";
import { GetApAgingTool } from "../tools/get-ap-aging.tool.js";
import { GetTransactionListTool } from "../tools/get-transaction-list.tool.js";
import { QueryQboTool } from "../tools/query-qbo.tool.js";
import { PrepareJournalEntryTool } from "../tools/prepare-journal-entry.tool.js";
import { ConfirmJournalEntryTool } from "../tools/confirm-journal-entry.tool.js";
import { GetTransactionPdfTool } from "../tools/get-transaction-pdf.tool.js";

export function registerAllTools(server: McpServer): void {
  RegisterTool(server, CreateCustomerTool);
  RegisterTool(server, GetCustomerTool);
  RegisterTool(server, UpdateCustomerTool);
  RegisterTool(server, DeleteCustomerTool);
  RegisterTool(server, SearchCustomersTool);
  RegisterTool(server, CreateEstimateTool);
  RegisterTool(server, GetEstimateTool);
  RegisterTool(server, UpdateEstimateTool);
  RegisterTool(server, DeleteEstimateTool);
  RegisterTool(server, SearchEstimatesTool);
  RegisterTool(server, CreateBillTool);
  RegisterTool(server, UpdateBillTool);
  RegisterTool(server, DeleteBillTool);
  RegisterTool(server, GetBillTool);
  RegisterTool(server, SearchBillsTool);
  RegisterTool(server, ReadInvoiceTool);
  RegisterTool(server, SearchInvoicesTool);
  RegisterTool(server, CreateInvoiceTool);
  RegisterTool(server, UpdateInvoiceTool);
  RegisterTool(server, CreateAccountTool);
  RegisterTool(server, UpdateAccountTool);
  RegisterTool(server, SearchAccountsTool);
  RegisterTool(server, ReadItemTool);
  RegisterTool(server, SearchItemsTool);
  RegisterTool(server, CreateItemTool);
  RegisterTool(server, UpdateItemTool);
  RegisterTool(server, CreateVendorTool);
  RegisterTool(server, UpdateVendorTool);
  RegisterTool(server, DeleteVendorTool);
  RegisterTool(server, GetVendorTool);
  RegisterTool(server, SearchVendorsTool);
  RegisterTool(server, CreateEmployeeTool);
  RegisterTool(server, GetEmployeeTool);
  RegisterTool(server, UpdateEmployeeTool);
  RegisterTool(server, SearchEmployeesTool);
  RegisterTool(server, CreateJournalEntryTool);
  RegisterTool(server, GetJournalEntryTool);
  RegisterTool(server, UpdateJournalEntryTool);
  RegisterTool(server, DeleteJournalEntryTool);
  RegisterTool(server, SearchJournalEntriesTool);
  RegisterTool(server, CreateBillPaymentTool);
  RegisterTool(server, GetBillPaymentTool);
  RegisterTool(server, UpdateBillPaymentTool);
  RegisterTool(server, DeleteBillPaymentTool);
  RegisterTool(server, SearchBillPaymentsTool);
  RegisterTool(server, CreatePurchaseTool);
  RegisterTool(server, GetPurchaseTool);
  RegisterTool(server, UpdatePurchaseTool);
  RegisterTool(server, DeletePurchaseTool);
  RegisterTool(server, SearchPurchasesTool);
  RegisterTool(server, GetProfitAndLossTool);
  RegisterTool(server, GetBalanceSheetTool);
  RegisterTool(server, GetTrialBalanceTool);
  RegisterTool(server, GetGeneralLedgerTool);
  RegisterTool(server, GetArAgingTool);
  RegisterTool(server, GetApAgingTool);
  RegisterTool(server, GetTransactionListTool);
  RegisterTool(server, QueryQboTool);
  RegisterTool(server, PrepareJournalEntryTool);
  RegisterTool(server, ConfirmJournalEntryTool);
  RegisterTool(server, GetTransactionPdfTool);
}
